name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy to Surge
    env:
      REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Surge and deploy
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: yarn build
      - run: |
          cd basic-wallet/
          yarn build
          cd build/
          mv index.html 200.html
          npm install -g surge
          surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
